// SPDX-License-Identifier: Apache-2.0

//go:build integration

// This file is Task 12 of the milestone-3 plan: a differential matrix suite
// comparing every builder-query shape the wrapped driver's recording
// wrappers (node_query.go's recordingNodeQuery, relationship_query.go's
// recordingRelationshipQuery) can recognize and serve against the raw pg
// driver used as an oracle, across the project's hand fixtures and a batch
// of seeded random graphs.
//
// # File placement: root package, not internal/engine
//
// The task brief originally called for this file to live at
// internal/engine/builder_differential_integration_test.go, mirroring
// random_differential_integration_test.go's placement. It lives here
// instead, at the repository root as part of package bloodtrail, for the
// same unavoidable reason staleness_integration_test.go's own top-of-file
// doc gives for that file: this suite exercises node_query.go's
// recordingNodeQuery and relationship_query.go's recordingRelationshipQuery
// -- the wrappers that recognize a Filter'd Count/FetchIDs/FetchTriples/
// FetchKinds/Query call and decide whether to serve it from the engine --
// and those wrappers are defined in the root package. internal/engine
// cannot see them, and even if the recognition logic itself lived in
// internal/engine (some of it does, in internal/engine/recognize), driving
// an actual *bloodtrail.Driver-wrapped transaction through them would
// require internal/engine to import the root package, which already
// imports internal/engine -- an import cycle. Putting this suite in the
// root package instead resolves that: the root package already imports
// internal/engine, so a test here can freely open a real *bloodtrail.Driver
// via dawgs.Open and drive builder queries through its wrapped
// transactions.
//
// Being in package bloodtrail (not bloodtrail_test) also gives this file
// the same white-box access staleness_integration_test.go relies on: the
// unexported Driver.engine field, used below for exactly one thing --
// engine.RebuildNow, a deterministic, on-demand rebuild after each graph is
// loaded, so every comparison below runs against a known-fresh snapshot
// with no dependency on a datapipe_status table or a poller's timing.
//
// # The matrix
//
// Two graph sources, each rebuilt from scratch and run through the full
// matrix below:
//
//   - The hand fixtures already used elsewhere in this repo's integration
//     suite (testdata/dawgs/traversal_shapes.json and adcs_fanout.json),
//     loaded together via graphtest.LoadDataset exactly as
//     driver_integration_test.go's loadDatasets does.
//   - 20 seeded random graphs (seeds 1..20), generated by
//     loadBuilderMatrixRandomGraph -- a local, size-bounded adaptation of
//     internal/graphtest's own LoadRandom (see that function's doc for why
//     it is adapted rather than reused unmodified: LoadRandom's 60-node,
//     180-edge sizing was tuned for milestone 2's much lighter path-query
//     differential suite, not for this suite's dense structural matrix,
//     which multiplies every node/edge kind by several anchor variants and
//     op families).
//
// For each loaded graph, runBuilderQueryDifferentialMatrix enumerates:
//
//   - Every node kind: a NodeSpec-shaped Count/FetchIDs/FetchKinds query
//     (query.Kind(query.Node(), k)).
//   - A bounded set of node-kind pairs: the same three ops via an any-of
//     KindIn query (query.KindIn(query.Node(), k1, k2)).
//   - Every edge kind, crossed with anchor variant {none, start-anchored,
//     end-anchored, both}: Count/FetchIDs/FetchTriples/FetchKinds, plus
//     endpoint-kind-constrained variants (query.Kind(query.Start()/End(),
//     k)), plus the two canonical .Query() projections -- unanchored pair
//     rows (Returning(StartID(), EndID())) and, for start-/end-anchored
//     specs, ordered step rows (Returning(EndID(), KindsOf(End()),
//     RelationshipID(), KindsOf(Relationship())) or its inbound mirror),
//     both with OrderBy(query.Order(query.Identity(query.Relationship()),
//     query.Ascending())) exactly as dawgs' own
//     traversal.shallowFetchRelationships issues it.
//
// Anchor ids are never hardcoded: firstEdgeAnchor and firstNodeKindOf derive
// a real start/end id (and the real kind each one carries) from the
// oracle's own data for the edge kind under test, alongside a fixed
// nonexistent-id sentinel (nonexistentID) that every anchor variant is also
// exercised against, expecting an empty but still-matching result on both
// sides.
//
// Count is compared exactly; FetchIDs/FetchTriples/FetchKinds/pair rows are
// compared as sets (sorted before comparison, in equalSlices); ordered step
// rows are compared as exact sequences (never sorted -- see collectStepRows).
//
// # Anti-vacuity
//
// A suite that only ever proves "the engine and PostgreSQL agree" without
// also proving "the engine actually answered, rather than delegating every
// single query" would be evidence-free: runBuilderQueryDifferentialMatrix
// tracks graphServed, the summed builder-served marker delta across every
// check it runs, and fails the graph outright if it never advances (a
// per-graph skip-guard). TestBuilderQueryDifferentialMatrix additionally
// tallies, across the whole suite, which of the nine op families (node
// count/ids/kinds, rel count/ids/triples/kinds, pair rows, step rows) were
// ever served at least once, failing at the end if any family was not --
// catching a recognizer regression that silently starts delegating just one
// family, which a single graph's aggregate graphServed > 0 check alone could
// never distinguish from "every other family compensated."
package bloodtrail

import (
	"context"
	"fmt"
	"math/rand"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/specterops/dawgs"
	"github.com/specterops/dawgs/drivers/pg"
	"github.com/specterops/dawgs/graph"
	"github.com/specterops/dawgs/opengraph"
	"github.com/specterops/dawgs/query"
	"github.com/specterops/dawgs/util/size"

	"github.com/MihhailSokolov/BloodTrail/internal/graphtest"
)

// --- Op-family tally (see this file's top doc, "Anti-vacuity"). ---

const (
	familyNodeCount  = "node_count"
	familyNodeIDs    = "node_ids"
	familyNodeKinds  = "node_kinds"
	familyRelCount   = "rel_count"
	familyRelIDs     = "rel_ids"
	familyRelTriples = "rel_triples"
	familyRelKinds   = "rel_kinds"
	familyPairRows   = "pair_rows"
	familyStepRows   = "step_rows"
)

// allOpFamilies lists every family TestBuilderQueryDifferentialMatrix
// requires to have been served at least once, anywhere in the suite.
var allOpFamilies = []string{
	familyNodeCount, familyNodeIDs, familyNodeKinds,
	familyRelCount, familyRelIDs, familyRelTriples, familyRelKinds,
	familyPairRows, familyStepRows,
}

// --- Graph source 1: the hand fixtures. ---

// builderMatrixFixturePaths are the same two opengraph datasets
// driver_integration_test.go's datasets loads, merged into one graph here
// the same way loadDatasets does (via graphtest.LoadDataset, called once
// per path against the same driver).
var builderMatrixFixturePaths = []string{
	"testdata/dawgs/traversal_shapes.json",
	"testdata/dawgs/adcs_fanout.json",
}

// builderMatrixFixtureKinds parses both fixture files (without loading them
// -- graphtest.LoadDataset does that separately) purely to recover their
// node/edge kind alphabets, the same way driver_integration_test.go's
// schemaFromDatasets does; duplicated here rather than called directly since
// schemaFromDatasets lives in package bloodtrail_test, a different package
// from this file's package bloodtrail.
func builderMatrixFixtureKinds(t *testing.T) (nodeKinds, edgeKinds graph.Kinds) {
	t.Helper()

	for _, path := range builderMatrixFixturePaths {
		f, err := os.Open(path)
		if err != nil {
			t.Fatalf("open %s: %v", path, err)
		}
		doc, err := opengraph.ParseDocument(f)
		_ = f.Close()
		if err != nil {
			t.Fatalf("parse %s: %v", path, err)
		}

		nk, ek := doc.Graph.Kinds()
		nodeKinds = nodeKinds.Add(nk...)
		edgeKinds = edgeKinds.Add(ek...)
	}

	return nodeKinds, edgeKinds
}

// --- Graph source 2: 20 seeded random graphs. ---

const (
	// builderMatrixRandomSeeds is the seed range TestBuilderQueryDifferentialMatrix
	// sweeps for its random-graph source; fixed for reproducibility, exactly
	// like internal/engine/random_differential_integration_test.go's own
	// randomDifferentialSeeds.
	builderMatrixRandomSeeds = 20

	// builderMatrixRandomNodes and builderMatrixRandomEdges size each random
	// graph. Deliberately smaller than graphtest.LoadRandom's fixed 60
	// nodes/180 edges: this suite's per-graph query count is already the
	// product of every node/edge kind, several anchor variants, and up to
	// four ops each, so keeping each individual graph small is what keeps
	// the full 20-seed sweep (see this file's top doc) under a couple of
	// minutes. The kind alphabet itself is unchanged (graphtest.
	// RandomNodeKinds/RandomEdgeKinds, 5/6 kinds) so the matrix's shape is
	// identical to what a full-size LoadRandom graph would produce, just
	// with less data to scan per query.
	builderMatrixRandomNodes = 40
	builderMatrixRandomEdges = 120
)

// loadBuilderMatrixRandomGraph generates a pseudo-random graph from seed
// into pgDriver's default graph, replicating graphtest.LoadRandom's exact
// generation algorithm (independent uniform draws for each node's kind and
// each edge's endpoints/kind, nodes via a write transaction so their ids are
// known, edges via BatchOperation) at builderMatrixRandomNodes/
// builderMatrixRandomEdges scale instead of LoadRandom's fixed 60/180 -- see
// those consts' doc for why this suite needs its own, smaller sizing rather
// than calling the shared, exported graphtest.LoadRandom directly.
// graphtest.LoadRandom itself is left completely untouched: it is shared
// infrastructure internal/engine's own random differential suite already
// depends on at its documented size, and changing that size would be an
// unrelated, unnecessary risk to take on for this task.
//
// Reuses graphtest.RandomNodeKinds/RandomEdgeKinds/GraphName so a caller
// comparing this suite's random graphs against internal/engine's own knows
// they are drawn from the identical kind alphabet, just a different
// (smaller) node/edge count.
func loadBuilderMatrixRandomGraph(t *testing.T, pgDriver *pg.Driver, seed int64) {
	t.Helper()
	ctx := context.Background()

	rng := rand.New(rand.NewSource(seed))

	schema := graph.Schema{Graphs: []graph.Graph{{Name: graphtest.GraphName, Nodes: graphtest.RandomNodeKinds, Edges: graphtest.RandomEdgeKinds}}}
	if err := pgDriver.AssertSchema(ctx, schema); err != nil {
		t.Fatalf("builder matrix: random graph (seed=%d): assert schema: %v", seed, err)
	}

	ids := make([]graph.ID, builderMatrixRandomNodes)
	if err := pgDriver.WriteTransaction(ctx, func(tx graph.Transaction) error {
		for i := range ids {
			kind := graphtest.RandomNodeKinds[rng.Intn(len(graphtest.RandomNodeKinds))]

			node, err := tx.CreateNode(graph.NewProperties(), kind)
			if err != nil {
				return err
			}
			ids[i] = node.ID
		}
		return nil
	}); err != nil {
		t.Fatalf("builder matrix: random graph (seed=%d): create nodes: %v", seed, err)
	}

	if err := pgDriver.BatchOperation(ctx, func(batch graph.Batch) error {
		for i := 0; i < builderMatrixRandomEdges; i++ {
			start := ids[rng.Intn(len(ids))]
			end := ids[rng.Intn(len(ids))]
			kind := graphtest.RandomEdgeKinds[rng.Intn(len(graphtest.RandomEdgeKinds))]

			// CreateRelationship, not the deprecated CreateRelationshipByIDs
			// graphtest.LoadRandom itself still uses (shared infra this
			// function otherwise mirrors, left untouched -- see this
			// function's own doc): the two are exactly equivalent (pg's own
			// batch.CreateRelationshipByIDs is a thin wrapper that builds
			// the same *graph.Relationship, ID left zero, and calls this),
			// so this file's own code can use the non-deprecated spelling
			// with no behavior change.
			if err := batch.CreateRelationship(graph.NewRelationship(0, start, end, graph.NewProperties(), kind)); err != nil {
				return err
			}
		}
		return nil
	}); err != nil {
		t.Fatalf("builder matrix: random graph (seed=%d): create edges: %v", seed, err)
	}
}

// --- The nonexistent-id sentinel every anchor variant is also run against. ---

// nonexistentID is the id every anchor variant below also exercises,
// expecting an empty (but still oracle-matching) result: PostgreSQL's own
// id columns are BIGSERIAL, assigning ids starting at 1, so 0 is never a
// database id any dataset or generator in this suite could produce.
// assertSentinelIDAbsent verifies this assumption directly, once per graph,
// rather than trusting it silently.
const nonexistentID = graph.ID(0)

// assertSentinelIDAbsent fails the test outright if nonexistentID somehow
// exists as a node or relationship id in oracle's current data -- a defensive
// check for the "expect empty results" contract every anchor variant's
// nonexistent-id case below relies on.
func assertSentinelIDAbsent(t *testing.T, ctx context.Context, oracle graph.Database) {
	t.Helper()

	if n := nodeCountByCriteria(t, ctx, oracle, query.Equals(query.NodeID(), nonexistentID)); n != 0 {
		t.Fatalf("sentinel id %d unexpectedly exists as a node (count=%d); this suite's nonexistent-id anchor variants assume it never does", nonexistentID, n)
	}
	if n := relCountByCriteria(t, ctx, oracle, query.Equals(query.RelationshipID(), nonexistentID)); n != 0 {
		t.Fatalf("sentinel id %d unexpectedly exists as a relationship (count=%d); this suite's nonexistent-id anchor variants assume it never does", nonexistentID, n)
	}
}

// --- Criteria-based query helpers, run identically against bt and oracle. ---
//
// These mirror engine_serving_integration_test.go's kind-keyed
// nodeCountByKind/relCountByKind/etc., generalized to take an arbitrary
// graph.Criteria (a bare kind filter, a KindIn any-of, or a full
// And(kind, id, endpoint-kind) conjunction) instead of a single kind, since
// this suite's matrix needs far more criteria shapes than "by one kind."

func nodeCountByCriteria(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria) int64 {
	t.Helper()

	var count int64
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		n, err := tx.Nodes().Filter(criteria).Count()
		count = n
		return err
	}); err != nil {
		t.Fatalf("Nodes().Filter(...).Count(): %v", err)
	}
	return count
}

func nodeIDsByCriteria(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria) []graph.ID {
	t.Helper()

	var ids []graph.ID
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		return tx.Nodes().Filter(criteria).FetchIDs(func(cursor graph.Cursor[graph.ID]) error {
			for id := range cursor.Chan() {
				ids = append(ids, id)
			}
			return cursor.Error()
		})
	}); err != nil {
		t.Fatalf("Nodes().Filter(...).FetchIDs(): %v", err)
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	return ids
}

// canonicalKindsRow is graph.KindsResult (nodes) reduced to a comparable
// value: graph.KindsResult itself holds a graph.Kinds slice, which cannot be
// compared with == (and so cannot satisfy a `comparable` type parameter),
// but a node's own kind *list* is unordered from either driver's
// perspective, so its names are sorted and joined into one string here --
// canonicalizeKindNames -- before the row is otherwise treated as plain,
// comparable data.
type canonicalKindsRow struct {
	id    graph.ID
	kinds string
}

// canonicalizeKindNames renders kinds as a sorted, comma-joined string, so
// two kind lists that carry the same kinds in different orders (e.g. one
// side derived from a bitset's iteration order, the other from a SQL
// array) compare equal.
func canonicalizeKindNames(kinds graph.Kinds) string {
	names := append([]string(nil), kinds.Strings()...)
	sort.Strings(names)
	return strings.Join(names, ",")
}

func nodeKindsByCriteria(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria) []canonicalKindsRow {
	t.Helper()

	var rows []canonicalKindsRow
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		return tx.Nodes().Filter(criteria).FetchKinds(func(cursor graph.Cursor[graph.KindsResult]) error {
			for row := range cursor.Chan() {
				rows = append(rows, canonicalKindsRow{id: row.ID, kinds: canonicalizeKindNames(row.Kinds)})
			}
			return cursor.Error()
		})
	}); err != nil {
		t.Fatalf("Nodes().Filter(...).FetchKinds(): %v", err)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].id < rows[j].id })
	return rows
}

func relCountByCriteria(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria) int64 {
	t.Helper()

	var count int64
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		n, err := tx.Relationships().Filter(criteria).Count()
		count = n
		return err
	}); err != nil {
		t.Fatalf("Relationships().Filter(...).Count(): %v", err)
	}
	return count
}

func relIDsByCriteria(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria) []graph.ID {
	t.Helper()

	var ids []graph.ID
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		return tx.Relationships().Filter(criteria).FetchIDs(func(cursor graph.Cursor[graph.ID]) error {
			for id := range cursor.Chan() {
				ids = append(ids, id)
			}
			return cursor.Error()
		})
	}); err != nil {
		t.Fatalf("Relationships().Filter(...).FetchIDs(): %v", err)
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	return ids
}

func relTriplesByCriteria(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria) []graph.RelationshipTripleResult {
	t.Helper()

	var triples []graph.RelationshipTripleResult
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		return tx.Relationships().Filter(criteria).FetchTriples(func(cursor graph.Cursor[graph.RelationshipTripleResult]) error {
			for triple := range cursor.Chan() {
				triples = append(triples, triple)
			}
			return cursor.Error()
		})
	}); err != nil {
		t.Fatalf("Relationships().Filter(...).FetchTriples(): %v", err)
	}
	sort.Slice(triples, func(i, j int) bool { return triples[i].ID < triples[j].ID })
	return triples
}

func relKindsByCriteria(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria) []graph.RelationshipKindsResult {
	t.Helper()

	var rows []graph.RelationshipKindsResult
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		return tx.Relationships().Filter(criteria).FetchKinds(func(cursor graph.Cursor[graph.RelationshipKindsResult]) error {
			for row := range cursor.Chan() {
				rows = append(rows, row)
			}
			return cursor.Error()
		})
	}); err != nil {
		t.Fatalf("Relationships().Filter(...).FetchKinds(): %v", err)
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].ID < rows[j].ID })
	return rows
}

// pairRow is one row of the ProjectionStartEnd .Query() shape
// (query.Returning(query.StartID(), query.EndID())) -- dawgs' own
// container.FetchDirectedGraph issues exactly this against an unanchored
// kind scan.
type pairRow struct {
	start, end graph.ID
}

// collectPairRows runs tx.Relationships().Filter(criteria).Query(...,
// query.Returning(query.StartID(), query.EndID())) through db, sorted
// ascending by (start, end) so two independently collected slices (bt vs.
// oracle) compare as sets via equalSlices.
func collectPairRows(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria) []pairRow {
	t.Helper()

	var rows []pairRow
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		return tx.Relationships().Filter(criteria).Query(func(results graph.Result) error {
			var start, end graph.ID
			for results.Next() {
				if err := results.Scan(&start, &end); err != nil {
					return err
				}
				rows = append(rows, pairRow{start: start, end: end})
			}
			return results.Error()
		}, query.Returning(query.StartID(), query.EndID()))
	}); err != nil {
		t.Fatalf("Relationships().Filter(...).Query(pair rows): %v", err)
	}

	sort.Slice(rows, func(i, j int) bool {
		if rows[i].start != rows[j].start {
			return rows[i].start < rows[j].start
		}
		return rows[i].end < rows[j].end
	})
	return rows
}

// stepRow is one row of either step .Query() shape -- ProjectionStepOutbound
// (far side "e") or ProjectionStepInbound (far side "s") -- dawgs' own
// traversal.shallowFetchRelationships issues for a single BFS step. farKinds
// is canonicalized the same way canonicalKindsRow's is, for the same reason
// (a graph.Kinds slice cannot satisfy `comparable`, and a node's own kind
// list is unordered data regardless).
type stepRow struct {
	farID    graph.ID
	farKinds string
	relID    graph.ID
	relKind  string
}

// collectStepRows runs tx.Relationships().Filter(criteria).OrderBy(query.
// Order(query.Identity(query.Relationship()), query.Ascending())).Query(...)
// through db, requesting the outbound projection (Returning(EndID(),
// KindsOf(End()), RelationshipID(), KindsOf(Relationship()))) when outbound
// is true, or its inbound mirror (Returning(StartID(), KindsOf(Start()),
// RelationshipID(), KindsOf(Relationship()))) otherwise -- exactly the two
// shapes shallowFetchRelationships builds for an outbound/inbound BFS step.
//
// Unlike every other collect*/​*ByCriteria helper in this file, the returned
// rows are NOT sorted: this suite compares step rows as an exact ordered
// SEQUENCE (the whole point of the OrderBy above), so preserving each side's
// own natural query order is the point, not an oversight.
func collectStepRows(t *testing.T, ctx context.Context, db graph.Database, criteria graph.Criteria, outbound bool) []stepRow {
	t.Helper()

	var rows []stepRow
	if err := db.ReadTransaction(ctx, func(tx graph.Transaction) error {
		q := tx.Relationships().Filter(criteria).OrderBy(query.Order(query.Identity(query.Relationship()), query.Ascending()))

		var returning graph.Criteria
		if outbound {
			returning = query.Returning(query.EndID(), query.KindsOf(query.End()), query.RelationshipID(), query.KindsOf(query.Relationship()))
		} else {
			returning = query.Returning(query.StartID(), query.KindsOf(query.Start()), query.RelationshipID(), query.KindsOf(query.Relationship()))
		}

		return q.Query(func(results graph.Result) error {
			var (
				farID    graph.ID
				farKinds graph.Kinds
				relID    graph.ID
				relKind  graph.Kind
			)
			for results.Next() {
				if err := results.Scan(&farID, &farKinds, &relID, &relKind); err != nil {
					return err
				}
				rows = append(rows, stepRow{
					farID:    farID,
					farKinds: canonicalizeKindNames(farKinds),
					relID:    relID,
					relKind:  relKind.String(),
				})
			}
			return results.Error()
		}, returning)
	}); err != nil {
		t.Fatalf("Relationships().Filter(...).OrderBy(...).Query(step rows, outbound=%v): %v", outbound, err)
	}
	return rows
}

// equalSlices reports whether a and b hold the same elements in the same
// order. Every collect*/​*ByCriteria helper above sorts its own result
// (except collectStepRows, deliberately -- see its doc), so this single
// sequence-equality check backs both this suite's "compare as sets" and
// "compare as exact sequences" contracts: the sorting (or lack of it)
// happens before this is ever called, not inside it.
func equalSlices[T comparable](a, b []T) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// --- Served-delta tracking (see this file's top doc, "Anti-vacuity"). ---

// withBuilderServedDelta runs fn (a single call through bt) and returns how
// many additional builderServedMarker lines buf's captured log shows
// afterward -- 1 (or more, if fn happens to issue more than one query) if
// the engine actually served it, 0 if it delegated to PostgreSQL instead.
// builderServedMarker and markerCount are staleness_integration_test.go's
// own identifiers, reused here since this file shares its package
// (bloodtrail).
func withBuilderServedDelta(buf *lockedBuffer, fn func()) int {
	before := markerCount(buf, builderServedMarker)
	fn()
	return markerCount(buf, builderServedMarker) - before
}

// recordServed folds one check's served delta into both the whole-suite
// tally (keyed by op family, incremented at most meaningfully once per
// family -- further increments are harmless) and the calling graph's own
// running total, graphServed.
func recordServed(tally map[string]int, family string, delta int, graphServed *int) {
	if delta > 0 {
		tally[family]++
		*graphServed += delta
	}
}

// --- Per-op-family comparison + served-tracking checks. ---
//
// Each of these runs one op through both bt and oracle, compares the
// results (t.Errorf on mismatch -- deliberately not Fatalf, so one
// divergence does not hide any other divergence the rest of this graph's
// matrix might also turn up), and records bt's own served delta into tally/
// graphServed via recordServed.

func checkNodeCount(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria) {
	t.Helper()

	var got int64
	delta := withBuilderServedDelta(buf, func() { got = nodeCountByCriteria(t, ctx, bt, criteria) })
	want := nodeCountByCriteria(t, ctx, oracle, criteria)
	if got != want {
		t.Errorf("%s: Count() = %d, want %d (oracle)", label, got, want)
	}
	recordServed(tally, familyNodeCount, delta, graphServed)
}

func checkNodeFetchIDs(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria) {
	t.Helper()

	var got []graph.ID
	delta := withBuilderServedDelta(buf, func() { got = nodeIDsByCriteria(t, ctx, bt, criteria) })
	want := nodeIDsByCriteria(t, ctx, oracle, criteria)
	if !equalSlices(got, want) {
		t.Errorf("%s: FetchIDs() = %v, want %v (oracle)", label, got, want)
	}
	recordServed(tally, familyNodeIDs, delta, graphServed)
}

func checkNodeFetchKinds(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria) {
	t.Helper()

	var got []canonicalKindsRow
	delta := withBuilderServedDelta(buf, func() { got = nodeKindsByCriteria(t, ctx, bt, criteria) })
	want := nodeKindsByCriteria(t, ctx, oracle, criteria)
	if !equalSlices(got, want) {
		t.Errorf("%s: FetchKinds() = %+v, want %+v (oracle)", label, got, want)
	}
	recordServed(tally, familyNodeKinds, delta, graphServed)
}

func checkRelCount(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria) {
	t.Helper()

	var got int64
	delta := withBuilderServedDelta(buf, func() { got = relCountByCriteria(t, ctx, bt, criteria) })
	want := relCountByCriteria(t, ctx, oracle, criteria)
	if got != want {
		t.Errorf("%s: Count() = %d, want %d (oracle)", label, got, want)
	}
	recordServed(tally, familyRelCount, delta, graphServed)
}

func checkRelFetchIDs(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria) {
	t.Helper()

	var got []graph.ID
	delta := withBuilderServedDelta(buf, func() { got = relIDsByCriteria(t, ctx, bt, criteria) })
	want := relIDsByCriteria(t, ctx, oracle, criteria)
	if !equalSlices(got, want) {
		t.Errorf("%s: FetchIDs() = %v, want %v (oracle)", label, got, want)
	}
	recordServed(tally, familyRelIDs, delta, graphServed)
}

func checkRelFetchTriples(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria) {
	t.Helper()

	var got []graph.RelationshipTripleResult
	delta := withBuilderServedDelta(buf, func() { got = relTriplesByCriteria(t, ctx, bt, criteria) })
	want := relTriplesByCriteria(t, ctx, oracle, criteria)
	if !equalSlices(got, want) {
		t.Errorf("%s: FetchTriples() = %+v, want %+v (oracle)", label, got, want)
	}
	recordServed(tally, familyRelTriples, delta, graphServed)
}

func checkRelFetchKinds(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria) {
	t.Helper()

	var got []graph.RelationshipKindsResult
	delta := withBuilderServedDelta(buf, func() { got = relKindsByCriteria(t, ctx, bt, criteria) })
	want := relKindsByCriteria(t, ctx, oracle, criteria)
	if !equalSlices(got, want) {
		t.Errorf("%s: FetchKinds() = %+v, want %+v (oracle)", label, got, want)
	}
	recordServed(tally, familyRelKinds, delta, graphServed)
}

func checkPairRows(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria) {
	t.Helper()

	var got []pairRow
	delta := withBuilderServedDelta(buf, func() { got = collectPairRows(t, ctx, bt, criteria) })
	want := collectPairRows(t, ctx, oracle, criteria)
	if !equalSlices(got, want) {
		t.Errorf("%s: pair rows = %+v, want %+v (oracle)", label, got, want)
	}
	recordServed(tally, familyPairRows, delta, graphServed)
}

func checkStepRows(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, graphServed *int, label string, criteria graph.Criteria, outbound bool) {
	t.Helper()

	var got []stepRow
	delta := withBuilderServedDelta(buf, func() { got = collectStepRows(t, ctx, bt, criteria, outbound) })
	want := collectStepRows(t, ctx, oracle, criteria, outbound)
	if !equalSlices(got, want) {
		t.Errorf("%s: step rows (outbound=%v) = %+v, want %+v (oracle)", label, outbound, got, want)
	}
	recordServed(tally, familyStepRows, delta, graphServed)
}

// --- Criteria construction and anchor discovery. ---

// relCriteria builds the single graph.Criteria a RelSpec-shaped query needs
// -- always exactly one Filter call (recognize.FromRelCriteria's accepted
// shape) -- combining an edge-kind KindIn with any of a start/end id
// equality and a start/end endpoint-kind constraint the caller supplies.
// Exactly one part (the bare KindIn) is returned unwrapped when nothing else
// is requested, matching the bare-KindMatcher shape BloodHound's own
// builder queries construct; two or more parts are combined with query.And.
func relCriteria(edgeKind graph.Kind, startID, endID *graph.ID, startKind, endKind graph.Kind) graph.Criteria {
	parts := []graph.Criteria{query.KindIn(query.Relationship(), edgeKind)}

	if startID != nil {
		parts = append(parts, query.Equals(query.StartID(), *startID))
	}
	if endID != nil {
		parts = append(parts, query.Equals(query.EndID(), *endID))
	}
	if startKind != nil {
		parts = append(parts, query.Kind(query.Start(), startKind))
	}
	if endKind != nil {
		parts = append(parts, query.Kind(query.End(), endKind))
	}

	if len(parts) == 1 {
		return parts[0]
	}
	return query.And(parts...)
}

// kindPairCap bounds how many node-kind pairs selectKindPairs returns:
// the fixtures graph alone carries 13 node kinds (78 unordered pairs), and
// testing every one of them, at three ops apiece, across 21 graphs would
// push this suite well past a sane runtime for no material extra coverage
// -- any-of kind matching is the same bitset-union operation regardless of
// which two kinds are named.
const kindPairCap = 20

// selectKindPairs returns every unordered pair of distinct kinds in kinds,
// downsampled to at most maxPairs by taking an evenly spaced subset
// (deterministic, so a failure reproduces identically on rerun) whenever the
// full combinatorial count would exceed it.
func selectKindPairs(kinds graph.Kinds, maxPairs int) [][2]graph.Kind {
	var all [][2]graph.Kind
	for i := 0; i < len(kinds); i++ {
		for j := i + 1; j < len(kinds); j++ {
			all = append(all, [2]graph.Kind{kinds[i], kinds[j]})
		}
	}

	if maxPairs <= 0 || len(all) <= maxPairs {
		return all
	}

	selected := make([][2]graph.Kind, 0, maxPairs)
	step := float64(len(all)) / float64(maxPairs)
	for i := 0; i < maxPairs; i++ {
		selected = append(selected, all[int(float64(i)*step)])
	}
	return selected
}

// firstEdgeAnchor derives a real (start, end) id pair for kind directly from
// oracle's own data -- the first (by relationship id) relationship of that
// kind -- rather than any hardcoded id. ok is false when the graph currently
// has no relationship of this kind, in which case the caller skips the
// existing-anchor variants for it (the nonexistent-id variant, run
// unconditionally, still exercises the anchored code paths for such a
// kind).
func firstEdgeAnchor(t *testing.T, ctx context.Context, oracle graph.Database, kind graph.Kind) (start, end graph.ID, ok bool) {
	t.Helper()

	triples := relTriplesByCriteria(t, ctx, oracle, query.KindIn(query.Relationship(), kind))
	if len(triples) == 0 {
		return 0, 0, false
	}
	return triples[0].StartID, triples[0].EndID, true
}

// firstNodeKindOf derives the first graph.Kind id itself carries, again
// read directly off oracle's data. Used to build a non-trivial (likely to
// actually match something) endpoint-kind constraint for the
// endpoint-kind-constrained variants below, rather than picking an arbitrary
// kind from the graph's alphabet that may have nothing to do with the
// anchor node in question.
func firstNodeKindOf(t *testing.T, ctx context.Context, oracle graph.Database, id graph.ID) (graph.Kind, bool) {
	t.Helper()

	var kinds graph.Kinds
	if err := oracle.ReadTransaction(ctx, func(tx graph.Transaction) error {
		node, err := tx.Nodes().Filter(query.Equals(query.NodeID(), id)).First()
		if err != nil {
			return err
		}
		kinds = node.Kinds
		return nil
	}); err != nil {
		t.Fatalf("fetch node %d: %v", id, err)
	}

	if len(kinds) == 0 {
		return nil, false
	}
	return kinds[0], true
}

// --- The matrix itself. ---

// runBuilderQueryDifferentialMatrix runs this file's whole differential
// matrix (see the top-of-file doc) against one already-loaded, already
// rebuilt graph, comparing bt (the wrapped driver under test) against
// oracle (the raw pg driver oracle) for every node kind, a bounded set of
// node-kind pairs, and every edge kind crossed with anchor variant,
// endpoint-kind constraint, and the two .Query() projections.
//
// It fails the calling graph outright (t.Fatalf) if graphServed -- the
// summed builder-served marker delta across every check this function
// runs -- never advances past zero: a graph whose every single query
// delegated to PostgreSQL proves nothing about the serving stack this suite
// exists to validate (see this file's top doc, "Anti-vacuity").
func runBuilderQueryDifferentialMatrix(t *testing.T, ctx context.Context, bt, oracle graph.Database, buf *lockedBuffer, tally map[string]int, nodeKinds, edgeKinds graph.Kinds) {
	t.Helper()

	assertSentinelIDAbsent(t, ctx, oracle)

	graphServed := 0

	// --- Every node kind: NodeSpec-shaped Count/FetchIDs/FetchKinds. ---
	for _, kind := range nodeKinds {
		crit := query.Kind(query.Node(), kind)
		label := fmt.Sprintf("node kind=%s", kind)

		checkNodeCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
		checkNodeFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
		checkNodeFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
	}

	// --- A bounded set of node-kind pairs: the same three ops, any-of. ---
	for _, pair := range selectKindPairs(nodeKinds, kindPairCap) {
		crit := query.KindIn(query.Node(), pair[0], pair[1])
		label := fmt.Sprintf("node kinds=%s|%s (any-of)", pair[0], pair[1])

		checkNodeCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
		checkNodeFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
		checkNodeFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
	}

	// --- Every edge kind x anchor variant, endpoint-kind constraints, and
	// the two .Query() projections. ---
	missingID := nonexistentID
	for _, kind := range edgeKinds {
		anchorStart, anchorEnd, hasEdge := firstEdgeAnchor(t, ctx, oracle, kind)

		var (
			startKind, endKind         graph.Kind
			haveStartKind, haveEndKind bool
		)
		if hasEdge {
			startKind, haveStartKind = firstNodeKindOf(t, ctx, oracle, anchorStart)
			endKind, haveEndKind = firstNodeKindOf(t, ctx, oracle, anchorEnd)
		}
		// Fall back to an arbitrary (but still real, present-in-this-graph)
		// node kind when this edge kind currently has no edge to derive one
		// from -- still a well-formed, if less likely to match, constraint.
		if !haveStartKind {
			startKind = nodeKinds[0]
		}
		if !haveEndKind {
			endKind = nodeKinds[len(nodeKinds)-1]
		}

		// anchor = none, plus the unanchored pair-rows projection.
		kindOnly := relCriteria(kind, nil, nil, nil, nil)
		label := fmt.Sprintf("edge kind=%s anchor=none", kind)
		checkRelCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, kindOnly)
		checkRelFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, kindOnly)
		checkRelFetchTriples(t, ctx, bt, oracle, buf, tally, &graphServed, label, kindOnly)
		checkRelFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, kindOnly)
		checkPairRows(t, ctx, bt, oracle, buf, tally, &graphServed, label+" pairRows", kindOnly)

		// anchor = start, existing id (only when this kind has an edge) plus
		// the outbound step-rows projection.
		if hasEdge {
			crit := relCriteria(kind, &anchorStart, nil, nil, nil)
			label = fmt.Sprintf("edge kind=%s anchor=start(existing)", kind)
			checkRelCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchTriples(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkStepRows(t, ctx, bt, oracle, buf, tally, &graphServed, label+" stepRows", crit, true)
		}

		// anchor = start, nonexistent id -- unconditional, expect empty.
		{
			crit := relCriteria(kind, &missingID, nil, nil, nil)
			label = fmt.Sprintf("edge kind=%s anchor=start(nonexistent)", kind)
			checkRelCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchTriples(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkStepRows(t, ctx, bt, oracle, buf, tally, &graphServed, label+" stepRows", crit, true)
		}

		// anchor = end, existing id, plus the inbound step-rows mirror.
		if hasEdge {
			crit := relCriteria(kind, nil, &anchorEnd, nil, nil)
			label = fmt.Sprintf("edge kind=%s anchor=end(existing)", kind)
			checkRelCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchTriples(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkStepRows(t, ctx, bt, oracle, buf, tally, &graphServed, label+" stepRows", crit, false)
		}

		// anchor = end, nonexistent id -- unconditional, expect empty.
		{
			crit := relCriteria(kind, nil, &missingID, nil, nil)
			label = fmt.Sprintf("edge kind=%s anchor=end(nonexistent)", kind)
			checkRelCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchTriples(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkStepRows(t, ctx, bt, oracle, buf, tally, &graphServed, label+" stepRows", crit, false)
		}

		// anchor = both (existing ids only).
		if hasEdge {
			crit := relCriteria(kind, &anchorStart, &anchorEnd, nil, nil)
			label = fmt.Sprintf("edge kind=%s anchor=both", kind)
			checkRelCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchTriples(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
		}

		// Endpoint-kind-constrained variants: unanchored, but with the
		// start (resp. end) side further constrained to a real kind
		// derived from the graph's own data.
		{
			crit := relCriteria(kind, nil, nil, startKind, nil)
			label = fmt.Sprintf("edge kind=%s start-kind=%s", kind, startKind)
			checkRelCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchTriples(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
		}
		{
			crit := relCriteria(kind, nil, nil, nil, endKind)
			label = fmt.Sprintf("edge kind=%s end-kind=%s", kind, endKind)
			checkRelCount(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchIDs(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchTriples(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
			checkRelFetchKinds(t, ctx, bt, oracle, buf, tally, &graphServed, label, crit)
		}
	}

	if graphServed == 0 {
		t.Fatalf("builder-served marker never advanced across this graph's %d-node-kind/%d-edge-kind matrix -- every single query delegated to PostgreSQL, which proves nothing about the serving stack", len(nodeKinds), len(edgeKinds))
	}
}

// TestBuilderQueryDifferentialMatrix is Task 12's deliverable: opens a real
// *Driver (bt) alongside a raw pg driver oracle on the same PostgreSQL
// database, then runs runBuilderQueryDifferentialMatrix once for the hand
// fixtures and once per random-graph seed (1..builderMatrixRandomSeeds),
// wiping and reloading the graph and forcing a deterministic RebuildNow
// (via the unexported Driver.engine field -- see this file's top doc for
// why that access is available and needed here) before each run so every
// comparison sees a known-fresh snapshot.
//
// After every graph has run, it additionally asserts that all nine op
// families (allOpFamilies) were served by the engine at least once
// somewhere in the whole suite -- the whole-suite half of this file's
// anti-vacuity contract; each individual graph's own per-graph skip-guard
// is runBuilderQueryDifferentialMatrix's job (see its own doc).
func TestBuilderQueryDifferentialMatrix(t *testing.T) {
	dsn := graphtest.PGAvailable(t)

	// Every snapshot observed below is the direct, deterministic result of
	// this test's own RebuildNow calls, each made right after loading that
	// graph's own data -- waitForBootLoad (right after AssertSchema, below)
	// is what makes that true, not mere luck of timing: WipeGraph/LoadDataset
	// both write through pgDriver, the raw driver, never through bt's Apply
	// path, so nothing here bumps applyEpoch, and a still-in-flight boot-load
	// LoadSnapshot call would have no epoch check stopping it from adopting
	// AFTER this test's own explicit RebuildNow and silently overwriting the
	// freshly loaded fixture/seed graph with whatever (possibly stale,
	// possibly mid-wipe) state existed when it started reading. Waiting for
	// boot load to settle before any of that runs removes the race outright,
	// rather than merely arguing it away.
	buf := installLogCapture(t)

	ctx := context.Background()

	pgDriver, pool := graphtest.OpenPG(t, dsn)
	cfg := dawgs.Config{ConnectionString: dsn, GraphQueryMemoryLimit: size.Gibibyte, Pool: pool}

	bt, err := dawgs.Open(ctx, DriverName, cfg)
	if err != nil {
		t.Fatalf("open bloodtrail: %v", err)
	}
	defer func() { _ = bt.Close(ctx) }()

	d, ok := bt.(*Driver)
	if !ok {
		t.Fatalf("expected *Driver, got %T", bt)
	}
	// AssertSchema's default-graph target is tracked per driver instance
	// (not auto-discovered from the database by a freshly opened one), so
	// this wrapped driver needs its own call even though graphtest.OpenPG
	// already asserted the same graph, by name, for pgDriver above.
	if err := bt.AssertSchema(ctx, graph.Schema{DefaultGraph: graph.Graph{Name: graphtest.GraphName}}); err != nil {
		t.Fatalf("assert schema (bt): %v", err)
	}

	waitForBootLoad(t, d)

	oracle, err := dawgs.Open(ctx, pg.DriverName, cfg)
	if err != nil {
		t.Fatalf("open pg oracle: %v", err)
	}
	defer func() { _ = oracle.Close(ctx) }()
	if err := oracle.AssertSchema(ctx, graph.Schema{DefaultGraph: graph.Graph{Name: graphtest.GraphName}}); err != nil {
		t.Fatalf("assert schema (oracle): %v", err)
	}

	tally := make(map[string]int, len(allOpFamilies))

	// --- Graph 1: the hand fixtures. ---
	t.Run("fixtures", func(t *testing.T) {
		graphtest.WipeGraph(t, pgDriver)
		for _, path := range builderMatrixFixturePaths {
			graphtest.LoadDataset(t, pgDriver, path)
		}
		if err := d.engine.RebuildNow(ctx, "matrix_test"); err != nil {
			t.Fatalf("RebuildNow: %v", err)
		}

		nodeKinds, edgeKinds := builderMatrixFixtureKinds(t)
		runBuilderQueryDifferentialMatrix(t, ctx, bt, oracle, buf, tally, nodeKinds, edgeKinds)
	})

	// --- Write-through rerun: the SAME fixtures graph (no rewipe), mutated
	// through bt's own write path, then the identical matrix rerun with
	// RebuildCount pinned -- see runBuilderMatrixWriteThroughPreamble's own
	// doc for the full design. writeThroughPreambleEnabled (prebuilt_corpus_
	// integration_test.go, this same package) gates this phase, shared with
	// that file's own "writethrough" subtest; on by default since it is
	// cheap.
	if writeThroughPreambleEnabled() {
		t.Run("fixtures_writethrough", func(t *testing.T) {
			nodeKinds, edgeKinds := builderMatrixFixtureKinds(t)

			rebuilds := d.engine.RebuildCount()
			fallbacks := markerCount(buf, fallbackEnteredMarker)

			runBuilderMatrixWriteThroughPreamble(t, ctx, bt, oracle, pool, nodeKinds, edgeKinds)

			runBuilderQueryDifferentialMatrix(t, ctx, bt, oracle, buf, tally, nodeKinds, edgeKinds)

			assertRebuildCountUnchanged(t, d, rebuilds, t.Name())
			assertNoNewFallback(t, buf, fallbacks, t.Name())
		})
	}

	// --- Graphs 2..21: 20 seeded random graphs. ---
	for seed := int64(1); seed <= builderMatrixRandomSeeds; seed++ {
		t.Run(fmt.Sprintf("random/seed=%d", seed), func(t *testing.T) {
			graphtest.WipeGraph(t, pgDriver)
			loadBuilderMatrixRandomGraph(t, pgDriver, seed)
			if err := d.engine.RebuildNow(ctx, "matrix_test"); err != nil {
				t.Fatalf("RebuildNow (seed=%d): %v", seed, err)
			}

			runBuilderQueryDifferentialMatrix(t, ctx, bt, oracle, buf, tally, graphtest.RandomNodeKinds, graphtest.RandomEdgeKinds)
		})
	}

	for _, family := range allOpFamilies {
		if tally[family] == 0 {
			t.Errorf("op family %q was never served by the engine anywhere in this suite -- a recognizer regression affecting exactly this family would go unnoticed", family)
		}
	}
}

// runBuilderMatrixWriteThroughPreamble performs a small, standard mutation
// batch through bt against the "fixtures" graph already loaded by
// TestBuilderQueryDifferentialMatrix's own "fixtures" subtest, leaving the
// replica in write-through-derived (not rebuild-derived) state before the
// caller reruns runBuilderQueryDifferentialMatrix over the same graph --
// re-basing this suite's structural matrix on write-through, mirroring
// prebuilt_corpus_integration_test.go's own runCorpusWriteThroughPreamble
// for its 222-query corpus (see that function's doc for the shared design
// rationale: reuse already-proven write-observer-recognized shapes so this
// preamble carries no risk of tripping fallback by accident).
//
// Uses write-through's classes 1 (objectid upsert create), 2 (objectid upsert
// merge), 5 (batch.UpdateNodes kinds+deleted prop), and 7 (batch.
// DeleteRelationship by id) -- the same four prebuilt_corpus_integration_
// test.go's own preamble uses -- against nodeKinds[0]/edgeKinds[0] (real
// kinds this specific graph carries, derived by the caller's own
// builderMatrixFixtureKinds, never hardcoded) so the mutations are counted
// by, not invisible to, the structural matrix's own per-kind Count/FetchIDs/
// FetchKinds/FetchTriples/pair-row/step-row checks that follow.
func runBuilderMatrixWriteThroughPreamble(t *testing.T, ctx context.Context, bt, oracle graph.Database, pool *pgxpool.Pool, nodeKinds, edgeKinds graph.Kinds) {
	t.Helper()

	// Read BEFORE any write below -- see prebuilt_corpus_integration_test.go's
	// runCorpusWriteThroughPreamble's identical reasoning: class 2 must
	// merge onto a genuinely pre-existing node, not (by scan-order
	// accident) the brand-new one class 1 is about to create. This
	// fixtures graph carries exactly one objectid-bearing node today
	// (adcs_fanout.json's lone Group node); if a future fixture edit adds
	// none at all, this read comes back "" and class 2 below degrades to
	// upserting a fresh (rather than merged) node under that empty-string
	// objectid, which still exercises the same write shape, just without an
	// existing target to merge onto.
	existingOID := cypherStringValue(t, ctx, oracle, `MATCH (n) WHERE n.objectid IS NOT NULL RETURN n.objectid LIMIT 1`)

	// Asserted through a THROWAWAY *pg.Driver sharing bt's own connection
	// pool, never through bt (or pgDriver/oracle) itself -- see
	// prebuilt_corpus_integration_test.go's runCorpusWriteThroughPreamble
	// doc, "Why the constraint is asserted through a THROWAWAY driver, not
	// bt itself", for the full derivation. Every driver instance already in
	// scope by this point (bt, pgDriver, oracle) already asserted
	// graphtest.GraphName's schema at least once before this preamble runs,
	// so each one's own SchemaManager cache would fast-path a same-name
	// re-assert into a no-op that never issues the real CREATE UNIQUE INDEX
	// -- confirmed the same way for this file (PostgreSQL error 42P10 on
	// the very next UpdateNodeBy) before this fix.
	schema := graph.Schema{DefaultGraph: graph.Graph{
		Name:            graphtest.GraphName,
		NodeConstraints: []graph.Constraint{{Field: "objectid", Type: graph.BTreeIndex}},
	}}
	if err := pg.NewDriver(size.Gibibyte, pool).AssertSchema(ctx, schema); err != nil {
		t.Fatalf("write-through preamble: assert schema with objectid constraint: %v", err)
	}

	primaryKind := nodeKinds[0]
	tempKind := graph.StringKind("WT18MatrixTemp")
	taggedKind := graph.StringKind("WT18MatrixTagged")
	mergedKind := graph.StringKind("WT18MatrixMerged")

	// Class 1: objectid upsert creating a brand-new node of a REAL fixture
	// kind, counted by that kind's Count/FetchIDs/FetchKinds checks in the
	// rerun that follows.
	const newObjectID = "WT18-MatrixPreambleNode"
	if err := bt.BatchOperation(ctx, func(batch graph.Batch) error {
		return batch.UpdateNodeBy(objectIDUpdate(newObjectID, graph.NewProperties().Set("wt18temp", "gone-soon"), primaryKind, tempKind))
	}); err != nil {
		t.Fatalf("write-through preamble: objectid upsert create: %v", err)
	}

	newNodeResult, err := runCorpusQuery(t, ctx, bt, fmt.Sprintf(`MATCH (n) WHERE n.objectid = %s RETURN n`, cypherStringLiteral(newObjectID)))
	if err != nil {
		t.Fatalf("write-through preamble: locate new node: %v", err)
	}
	newIDs := extractNodeIDs(newNodeResult)
	if len(newIDs) != 1 {
		t.Fatalf("write-through preamble: locate new node: got %d nodes, want 1", len(newIDs))
	}
	newNodeID := newIDs[0]

	// Class 2: objectid upsert merging a kind onto whichever node
	// existingOID (read above, before any write) names.
	if err := bt.BatchOperation(ctx, func(batch graph.Batch) error {
		return batch.UpdateNodeBy(objectIDUpdate(existingOID, graph.NewProperties().Set("wt18merged", "yes"), mergedKind))
	}); err != nil {
		t.Fatalf("write-through preamble: objectid upsert merge: %v", err)
	}

	// Class 5: batch.UpdateNodes carrying AddedKinds/DeletedKinds and a
	// deleted property, targeting the class-1 node above by id.
	update := &graph.Node{ID: newNodeID, Kinds: graph.Kinds{taggedKind}, DeletedKinds: graph.Kinds{tempKind}, Properties: graph.NewProperties()}
	update.Properties.Delete("wt18temp")
	if err := bt.BatchOperation(ctx, func(batch graph.Batch) error {
		return batch.UpdateNodes([]*graph.Node{update})
	}); err != nil {
		t.Fatalf("write-through preamble: batch UpdateNodes: %v", err)
	}

	// Class 7: batch.DeleteRelationship by id -- a real edge of the
	// fixture's first edge kind, discovered via this file's own
	// relTriplesByCriteria (never hardcoded).
	triples := relTriplesByCriteria(t, ctx, oracle, query.KindIn(query.Relationship(), edgeKinds[0]))
	if len(triples) == 0 {
		t.Fatalf("write-through preamble: no existing %s relationship to delete", edgeKinds[0])
	}
	if err := bt.BatchOperation(ctx, func(batch graph.Batch) error {
		return batch.DeleteRelationship(triples[0].ID)
	}); err != nil {
		t.Fatalf("write-through preamble: DeleteRelationship: %v", err)
	}
}
